/* params.h — auto-generated by generate_ic.jl */
/* GravityProblem(1024; ε_max=0.9)       */
#define WAVELENGTH   3.1940891871679   /* cm */
#define AK_STEEP     0.38080929592657   /* kH/2 */
#define PHASE_SPEED  24   /* cm/s */
#define BOND_NUMBER  0.0071939830772929
#define FROUDE       0.42874909735042
#define G_ACCEL      981   /* cm/s² */
#define RHO_W        1   /* g/cm³ */
#define SIGMA_VAL    72   /* dyn/cm */
#define RESOLUTION   1024
