name = "ForcedInterfacialWaves"
uuid = "e5219359-20f7-449b-9a6e-3764ada0d72e"
version = "0.1.0"
authors = ["Vinod Kumar Kadari", "Nikhil"]

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
FresnelIntegrals = "88497964-e39a-11e9-0fb5-b1bf0ffe80fe"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
CommonSolve = "0.2"
FresnelIntegrals = "0.2"
QuadGK = "2"
julia = "1.9"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Printf", "Test"]
