%% Two-fluid capillary-gravity IVP solution
	clear;
	clc;
	close all;
	
	%% Number of spatial points
	Nx_plot = 2001;
	
	%% Dimensional physical parameters in CGS units
	U     = 26.7046;       % Uniform base flow speed [cm/s]
	g     = 981.0;         % Gravitational acceleration [cm/s^2]
	T = 72.0;          	   % Surface tension [dyn/cm]
	rho_l = 1.0;           % Lower-fluid density [g/cm^3]
	rho_u = 0.001;         % Upper-fluid density [g/cm^3]
	L     = 75.5996;       % Dimensional domain length [cm]
	
	%% Characteristic scales
	l_c = U^2/g;
	t_c = U/g;
	F_c = rho_l*U^2*l_c;
	
	%% Nondimensional parameters
	alpha = T/(rho_l*U^2*l_c);
	rho_r = rho_u/rho_l;
	
	beta  = (1.0 - rho_r)/(1.0 + rho_r);
	gamma_rho = 1.0/(1.0 + rho_r);
	
	%% Gravity and capillary wave roots
	discriminant = (1.0 + rho_r)^2 ...
	- 4.0*alpha*(1.0 - rho_r);
	
	if discriminant <= 0.0
	error(['The steady capillary-gravity roots are not ', ...
	'distinct positive real numbers.']);
	end
	
	k_l = ((1.0 + rho_r) + sqrt(discriminant))/(2.0*alpha);
	k_s = ((1.0 + rho_r) - sqrt(discriminant))/(2.0*alpha);
	
	%% Dimensional wavenumbers and wavelengths
	k_l_dim = k_l/l_c;
	k_s_dim = k_s/l_c;
	
	lambda_c = 2.0*pi/k_l_dim;	% Capillary wavelength
	lambda_g = 2.0*pi/k_s_dim;	% Gravity wavelength
	
	fprintf('alpha    = %.2e\n', alpha);
	fprintf('rho_r    = %.2e\n', rho_r);
	fprintf('k_s      = %.2e\n', k_s);
	fprintf('k_l      = %.2e\n', k_l);
	fprintf('lambda_c = %.2e cm\n', lambda_c);
	fprintf('lambda_g = %.2e cm\n', lambda_g);
	
	%% Nondimensional forcing amplitude
	F0_dim = 0.01*T;
	F0    = F0_dim/F_c;
	
	%% Nondimensional spatial grid
	x_grid = linspace(-L/2.0, L/2.0, Nx_plot)/l_c;
	
	% Remove x = 0 from the grid
	x_grid(abs(x_grid) < eps) = [];
	
	Nx = numel(x_grid);
	
	%% Quadrature parameters
	epsilon_pv = 1.0e-6;
	AbsTol     = 1.0e-10;
	RelTol     = 1.0e-8;
	
	k_max        = Inf;
	k_max_steady = Inf;
	% k_max_steady = 100.0;
	
	%% Give your data and output directories then comment Vinod's data and output directories
	% 		data_directory   = 'Give your simulation data folder path';
	% 		output_directory = 'Give folder path to save output figures';
	%% Vinod's data and output directories
	data_directory = '/home1/cluster_vinod/d_inf_depth_air_water_no_slip/bo25_lamda_8_52cm/new/two_fluids/capillary_gravity/new_grid/t28_7/para_if';
	output_directory = '/home1/cluster_vinod/d_inf_depth_air_water_no_slip/bo25_lamda_8_52cm/new/two_fluids/capillary_gravity/new_grid/t28_7/t28_7_fig10_jfm';
	
	if ~exist(output_directory, 'dir')
	mkdir(output_directory);
	end
	
	%% Simulation times stored as hundredths of a second
	% Replace these values with the exact simulation file indices.
	time_indices = [1, 3, 7, 15, 25, 60, 145, 300];
	% time_indices = 300; % To plot at a single time
	
	for it = 1:numel(time_indices)
	
	time_index = time_indices(it);
	
	% Dimensional and nondimensional times
	t_dim = time_index/100.0;
	t     = t_dim/t_c;
	
	%% Read simulation data
	simulation_file = fullfile( ...
	data_directory, ...
	sprintf('if_%d.csv', time_index));
	
	if ~exist(simulation_file, 'file')
	warning('Simulation file not found: %s', simulation_file);
	continue;
	end
	
	simulation_matrix = readmatrix( ...
	simulation_file, ...
	'NumHeaderLines', 1);
	
	% Columns 6 and 7 contain x and eta
	simulation_matrix = sortrows( ...
	simulation_matrix(:, [6, 7]), 1);
	
	x_sim   = simulation_matrix(:,1)/l_c;
	eta_sim = simulation_matrix(:,2)/l_c;
	
	%% Allocate theoretical solutions
	eta_ivp    = zeros(size(x_grid));
	if time_index == 300
	eta_steady = nan(size(x_grid));
	else
	eta_steady = [];
	end
	
	%% Evaluate the theoretical solution
	for ix = 1:Nx
	
	x = x_grid(ix);
	
	% Two-fluid dispersion function
	chi = @(k) sqrt( ...
	beta.*k + gamma_rho.*alpha.*k.^3);
	
	% Nominally time-independent contribution
	integrand_eta_s = @(k) ...
	2.0 .* cos(k.*x) ./ ...
	(alpha.*(k - k_l).*(k - k_s));
	
	% First time-dependent contribution
	integrand_I3 = @(k) ...
	-((1.0 + rho_r).*(k + chi(k))) ./ ...
	(1.0 - rho_r + alpha.*k.^2) .* ...
	cos(k.*(t - x) - t.*chi(k)) ./ ...
	(alpha.*(k - k_l).*(k - k_s));
	
	% Second time-dependent contribution
	integrand_I4 = @(k) ...
	-((1.0 + rho_r).*(k - chi(k))) ./ ...
	(1.0 - rho_r + alpha.*k.^2) .* ...
	cos(k.*(t - x) + t.*chi(k)) ./ ...
	(alpha.*(k - k_l).*(k - k_s));
	
	% Combine the terms before integration
	total_integrand = @(k) ...
	integrand_eta_s(k) ...
	+ integrand_I3(k) ...
	+ integrand_I4(k);
	
	% Integration below k_s
	integral_1 = integral( ...
	total_integrand, ...
	0.0, ...
	k_s - epsilon_pv, ...
	'AbsTol', AbsTol, ...
	'RelTol', RelTol);
	
	% Integration between k_s and k_l
	integral_2 = integral( ...
	total_integrand, ...
	k_s + epsilon_pv, ...
	k_l - epsilon_pv, ...
	'AbsTol', AbsTol, ...
	'RelTol', RelTol);
	
	% Integration above k_l
	integral_3 = integral( ...
	total_integrand, ...
	k_l + epsilon_pv, ...
	k_max, ...
	'AbsTol', AbsTol, ...
	'RelTol', RelTol);
	
	% Time-dependent IVP solution
	eta_ivp(ix) = -F0/(2.0*pi) ...
	* (integral_1 + integral_2 + integral_3);
	
	%% Classical steady solution calculating at a longer time(time_index = 300)
	if time_index == 300
	
	G_x_combined_integrand = @(k) ...
	cos(k.*x)./(k + k_s) ...
	- cos(k.*x)./(k + k_l);
	
	G_x = 1.0/(k_l - k_s) .* ...
	integral( ...
	G_x_combined_integrand, ...
	0.0, ...
	k_max_steady, ...
	'AbsTol', AbsTol, ...
	'RelTol', RelTol);
	
	if x > 0.0
	eta_steady(ix) = ...
	-2.0*F0/(alpha*(k_l - k_s)) ...
	.*sin(k_s*x) ...
	+ F0/(pi*alpha).*G_x;
	else
	eta_steady(ix) = ...
	-2.0*F0/(alpha*(k_l - k_s)) ...
	.*sin(k_l*x) ...
	+ F0/(pi*alpha).*G_x;
	end
	
	end
	end
	
	%% Plot theory and simulation
	%% For double column images
	FIG_SIZE_IN = [3.45 2.30];   % width x height in inches (good for 2-per-row)
	AX_LW   = 0.9; % axis box
	LW      = 1.8; % curves
	
	AX_FS   = 10;
	FS      = 10;    % tick numbers
	LABLE_FS = 12;   % x/y labels
	LEG_FS  = 10;     % legend
	
	fig = figure('Visible','on','Color','w','Renderer','painters');
	set(fig,'Units','inches','Position',[1 1 FIG_SIZE_IN]);
	tl = tiledlayout(fig,1,1,'Padding','compact','TileSpacing','compact');
	ax = nexttile(tl); hold(ax,'on');
	set(ax,'TickDir','out','LineWidth',AX_LW,'FontSize',AX_FS);
	set(ax,'XAxisLocation','bottom','YAxisLocation','left');
	
	hold on;
	
	%% Plot steady, simulation and IVP
	
	if time_index == 300
	
	% 1. Steady solution
	h1 = plot( ...
	x_grid, ...
	1.0e3*eta_steady, ...
	'k-', ...
	'LineWidth', LW);
	
	% 2. Simulation
	h2 = plot( ...
	x_sim, ...
	1.0e3*eta_sim, ...
	'r:', ...
	'LineWidth', LW);
	
	% 3. Theoretical IVP solution
	h3 = plot( ...
	x_grid, ...
	1.0e3*eta_ivp, ...
	'b--', ...
	'LineWidth', LW);
	
	lgd = legend( ...
	[h1 h2 h3], ...
	{'Steady', 'Simulation', 'Theory'}, ...
	'Interpreter', 'latex', ...
	'FontSize', LEG_FS, ...
	'Location', 'northeast');
	
	else
	
	% Simulation
	h2 = plot( ...
	x_sim, ...
	1.0e3*eta_sim, ...
	'r:', ...
	'LineWidth', LW);
	
	% Theoretical IVP solution
	h3 = plot( ...
	x_grid, ...
	1.0e3*eta_ivp, ...
	'b-.', ...
	'LineWidth', LW);
	
	lgd = legend( ...
	[h2 h3], ...
	{'Simulation', 'Theory'}, ...
	'Interpreter', 'latex', ...
	'FontSize', LEG_FS, ...
	'Location', 'northeast');
	
	end
	
	% Shorter line samples inside legend
	lgd.ItemTokenSize = [12, 9];
	
	xlabel( ...
	'$x$', ...
	'Interpreter', 'latex', ...
	'FontSize', LABLE_FS);
	
	ylabel( ...
	'$10^3\eta$', ...
	'Interpreter', 'latex', ...
	'FontSize', LABLE_FS);
	
	xlim([-5, 10]);
	ylim([-6, 13]);
	yticks([-4, 0, 4, 8]);
	
	set(ax,'Box','off');  % important
	
	% draw top/right frame lines
	delete(findall(ax,'Tag','TopRightFrame'));
	
	xl = xlim(ax);
	yl = ylim(ax);
	
	line(ax, ...
	[xl(1) xl(2)], ...
	[yl(2) yl(2)], ...
	'Color','k', ...
	'LineWidth',AX_LW, ...
	'Clipping','off', ...
	'HandleVisibility','off', ...
	'Tag','TopRightFrame');
	
	line(ax, ...
	[xl(2) xl(2)], ...
	[yl(1) yl(2)], ...
	'Color','k', ...
	'LineWidth',AX_LW, ...
	'Clipping','off', ...
	'HandleVisibility','off', ...
	'Tag','TopRightFrame');
	
	%% Save the figure
	output_name = sprintf( ...
	'figure10_t_%04d', ...
	time_index);
	
	exportgraphics( ...
	fig, ...
	fullfile( ...
	output_directory, ...
	[output_name, '.pdf']), ...
	'ContentType', 'vector', ...
	'BackgroundColor', 'white');
	
	exportgraphics( ...
	fig, ...
	fullfile( ...
	output_directory, ...
	[output_name, '.png']), ...
	'Resolution', 900, ...
	'BackgroundColor', 'white');
	end
