%% Two-fluid pure-gravity IVP: analytical and numerical CPV
	clear;
	clc;
	close all;
	
	%% Give your output directory and comment Vinod's output directory
	% 		output_directory   = 'give your output folder path';
	%% Vinod's output directory
	output_directory   = '/home1/cluster_vinod/d_inf_depth_air_water_no_slip/bo25_lamda_8_52cm/new/two_fluids/only_gravity_new_grid/t1_g/fig6_jfm_vinod';
	
	if ~exist(output_directory, 'dir')
	mkdir(output_directory);
	end
	
	%% Spatial regions
	% Analytical expressions are plotted outside a band around x = t.
	front_band = 1.0;
	
	%% Times and spatial resolution
	% The entries in time_indices are hundredths of a second.
	time_indices = [1, 7, 15, 40, 60, 100, 300, 500];
	% 		time_indices = 1; % To plot at a single time
	Nx_plot      = 2001;
	
	%% Dimensional physical parameters in CGS units
	g     = 981.0;       % Gravitational acceleration [cm/s^2]
	rho_l = 1.0;         % Lower-fluid density [g/cm^3]
	rho_u = 0.001;       % Upper-fluid density [g/cm^3]
	U     = 26.7046;     % Uniform base flow speed [cm/s]
	
	%% Characteristic scales
	l_c = U^2/g;
	t_c = U/g;
	F_c = rho_l*U^2*l_c;
	
	%% Nondimensional forcing amplitude
	T_reference = 72.0;
	F_nd             = T_reference/F_c;
	F0               = 0.01*F_nd;
	
	%% Density parameters
	rho_r     = rho_u/rho_l;
	beta      = (1.0 - rho_r)/(1.0 + rho_r);
	sqrt_beta = sqrt(beta);
	beta_sq   = beta^2;
	
	%% Fourier normalisation factors
	sqrt_2pi     = sqrt(2.0*pi);
	inv_sqrt_2pi = 1.0/sqrt_2pi;
	
	%% Plotting domain
	gravity_wavelength = 2.0*pi/beta;
	L                  = 4.0*gravity_wavelength;
	
	%% Integral parameters
	KMAX_analytical = 100.0;
	KMAX_cpv        = 100.0;
	
	AbsTol_ana = 1.0e-10;
	RelTol_ana = 1.0e-8;
	
	epsilon_cpv = 1.0e-6;
	AbsTol_cpv = 1.0e-10;
	RelTol_cpv = 1.0e-8;
	
	%% Loop over requested times
	for jt = 1:numel(time_indices)
	
	time_index = time_indices(jt);
	
	% Dimensional time [s] and nondimensional time
	t_dim = time_index/100.0;
	t     = t_dim/t_c;
	
	%% Nondimensional spatial grid
	x = linspace(-L/2.0, L/2.0, Nx_plot);
	
	% Remove x = 0 because the steady transformed expression
	% becomes numerically sensitive there.
	epsilon_x = 1.0e-6;
	x(abs(x) < epsilon_x) = [];
	
	N = numel(x);
	
	%% Regions relative to x = t point
	a = t - x;
	
	mask_left  = a >  front_band;
	mask_right = a < -front_band;
	mask_outer = mask_left | mask_right;
	
	x_abs = abs(x);
	
	%% Preallocate analytical arrays
	eta_analytical = nan(1, N);
	eta_transient  = nan(1, N);
	
	T1 = nan(1, N);
	T2 = nan(1, N);
	T3 = nan(1, N);
	T4 = nan(1, N);
	
	T1_xgt = nan(1, N);
	T2_xgt = nan(1, N);
	T3_xgt = nan(1, N);
	T4_xgt = nan(1, N);
	
	%% Analytical steady contribution T0
	T0a = -pi.*sin(beta.*x_abs);
	
	T0b = arrayfun(@(x_abs_value) ...
	integral( ...
	@(y) exp(-y.*x_abs_value) ...
	.*y./(beta_sq + y.^2), ...
	0.0, ...
	Inf, ...
	'AbsTol', AbsTol_ana, ...
	'RelTol', RelTol_ana), ...
	x_abs);
	
	T0 = (T0a + T0b)./(pi.*(1.0 + rho_r));
	
	eta_steady = F0.*T0;
	
	%% Analytical solution for x < t - front_band
	if any(mask_left)
	
	a_left = a(mask_left);
	
	% T1
	T1(mask_left) = ...
	-sin(beta.*x(mask_left))./(1.0 + rho_r);
	
	% T2
	T2_integrand = @(v, aa) ...
	exp(-2.0.*v.^2.*aa + v.*t.*sqrt_beta) ...
	.*v.^2 ...
	.*( ...
	sqrt_beta.*cos(v.*t.*sqrt_beta) ...
	+(2.0.*v - sqrt_beta) ...
	.*sin(v.*t.*sqrt_beta) ...
	) ...
	./(beta + (2.0.*v - sqrt_beta).^2);
	
	T2(mask_left) = ...
	-4.0./(pi.*(1.0 + rho_r).*beta) ...
	.*arrayfun(@(aa) ...
	integral( ...
	@(v) T2_integrand(v, aa), ...
	0.0, ...
	KMAX_analytical, ...
	'AbsTol', AbsTol_ana, ...
	'RelTol', RelTol_ana), ...
	a_left);
	
	% T3
	b_left = 0.5.*t.*sqrt_beta;
	
	X_left = b_left ...
	.*sqrt(2.0./(pi.*a_left));
	
	prefactor_left = ...
	(1.0./(pi*(1+rho_r)*sqrt_beta)) ...
	.*(1.0 + t./(2.0.*a_left));
	
	T3(mask_left) = ...
	prefactor_left ...
	.*sqrt(pi./(2.0.*a_left)) ...
	.*( ...
	cos(b_left.^2./a_left) ...
	.*(0.5 - fresnelc(X_left)) ...
	+ ...
	sin(b_left.^2./a_left) ...
	.*(0.5 - fresnels(X_left)) ...
	);
	
	% T4
	T4_integrand = @(v, aa) ...
	cos(v.^2.*aa + v.*t.*sqrt_beta) ...
	./(v + sqrt_beta);
	
	T4(mask_left) = ...
	-1.0./(pi.*(1.0 + rho_r)) ...
	.*arrayfun(@(aa) ...
	integral( ...
	@(v) T4_integrand(v, aa), ...
	0.0, ...
	KMAX_analytical, ...
	'AbsTol', AbsTol_ana, ...
	'RelTol', RelTol_ana), ...
	a_left);
	
	eta_transient(mask_left) = F0.*( ...
	T1(mask_left) ...
	+ T2(mask_left) ...
	+ T3(mask_left) ...
	+ T4(mask_left));
	
	eta_analytical(mask_left) = ...
	eta_steady(mask_left) ...
	+ eta_transient(mask_left);
	end
	
	%% Analytical solution for x > t + front_band
	if any(mask_right)
	
	% In the source formulation, a_right = t - x < 0.
	a_right = a(mask_right);
	
	% T1_xgt
	T1_xgt(mask_right) = ...
	sin(beta.*x(mask_right))./(1.0 + rho_r);
	
	% T2_xgt
	T2_xgt_integrand = @(v, aa) ...
	exp(2.0.*v.^2.*aa - v.*t.*sqrt_beta) ...
	.*v.^2 ...
	.*( ...
	sqrt_beta.*cos(v.*t.*sqrt_beta) ...
	-(2.0.*v - sqrt_beta) ...
	.*sin(v.*t.*sqrt_beta) ...
	) ...
	./(beta + (2.0.*v - sqrt_beta).^2);
	
	T2_xgt(mask_right) = ...
	-4.0./(pi.*(1.0 + rho_r).*beta) ...
	.*arrayfun(@(aa) ...
	integral( ...
	@(v) T2_xgt_integrand(v, aa), ...
	0.0, ...
	KMAX_analytical, ...
	'AbsTol', AbsTol_ana, ...
	'RelTol', RelTol_ana), ...
	a_right);
	
	% T3_xgt
	b_right = 0.5.*t.*sqrt_beta;
	
	X_right = b_right ...
	.*sqrt(2.0./(pi.*abs(a_right)));
	
	prefactor_right = ...
	(1.0./(pi*(1+rho_r)*sqrt_beta)) ...
	.*(1.0 + t./(2.0.*a_right));
	
	T3_xgt(mask_right) = ...
	prefactor_right ...
	.*sqrt(pi./(2.0.*abs(a_right))) ...
	.*( ...
	cos(b_right.^2./abs(a_right)) ...
	.*(0.5 + fresnelc(X_right)) ...
	+ ...
	sin(b_right.^2./abs(a_right)) ...
	.*(0.5 + fresnels(X_right)) ...
	);
	
	% T4_xgt
	T4_xgt_integrand = @(v, aa) ...
	cos(v.^2.*aa + v.*t.*sqrt_beta) ...
	./(v + sqrt_beta);
	
	T4_xgt(mask_right) = ...
	-1.0./(pi.*(1.0 + rho_r)) ...
	.*arrayfun(@(aa) ...
	integral( ...
	@(v) T4_xgt_integrand(v, aa), ...
	0.0, ...
	KMAX_analytical, ...
	'AbsTol', AbsTol_ana, ...
	'RelTol', RelTol_ana), ...
	a_right);
	
	eta_transient(mask_right) = F0.*( ...
	T1_xgt(mask_right) ...
	+ T2_xgt(mask_right) ...
	+ T3_xgt(mask_right) ...
	+ T4_xgt(mask_right));
	
	eta_analytical(mask_right) = ...
	eta_steady(mask_right) ...
	+ eta_transient(mask_right);
	end
	
	%% Direct numerical CPV solution
	eta_cpv_numerical = nan(1, N);
	
	for ix = 1:N
	
	xx = x(ix);
	
	% Form the complete integrand before integration so that
	% the singular contributions are treated together.
	combined_integrand = @(k) ...
	cos(k.*xx) ...
	./(pi.*(1.0 + rho_r).*(k - beta)) ...
	...
	-k.*cos( ...
	k.*(t - xx) - t.*sqrt(beta.*k)) ...
	./( ...
	2.0.*pi.*(1.0 - rho_r) ...
	.*(k - sqrt(beta.*k)) ...
	) ...
	...
	-k.*cos( ...
	k.*(t - xx) + t.*sqrt(beta.*k)) ...
	./( ...
	2.0.*pi.*(1.0 - rho_r) ...
	.*(k + sqrt(beta.*k)) ...
	);
	
	integral_below_pole = integral( ...
	combined_integrand, ...
	0.0, ...
	beta - epsilon_cpv, ...
	'RelTol', RelTol_cpv, ...
	'AbsTol', AbsTol_cpv, ...
	'ArrayValued', true);
	
	integral_above_pole = integral( ...
	combined_integrand, ...
	beta + epsilon_cpv, ...
	KMAX_cpv, ...
	'RelTol', RelTol_cpv, ...
	'AbsTol', AbsTol_cpv, ...
	'ArrayValued', true);
	
	eta_cpv_numerical(ix) = F0.*( ...
	integral_below_pole ...
	+ integral_above_pole);
	end
	
	%% Error between analytical and numerical CPV solutions
	
	% Difference is evaluated only where the analytical expression is used.
	error_difference = ...
	eta_analytical(mask_outer) ...
	- eta_cpv_numerical(mask_outer);
	
	% Maximum absolute error
	maximum_absolute_error = ...
	max(abs(error_difference), [], 'omitnan');
	
	% Global L-infinity relative error
	% Normalised by the maximum amplitude of the numerical CPV solution.
	reference_amplitude = ...
	max(abs(eta_cpv_numerical(mask_outer)), [], 'omitnan');
	
	relative_Linf_error = ...
	maximum_absolute_error./reference_amplitude;
	
	% Relative L2 error
	relative_L2_error = ...
	norm(error_difference, 2) ...
	./norm(eta_cpv_numerical(mask_outer), 2);
	
	%% Print error measures
	fprintf('\nTime index = %d\n', time_index);
	fprintf('t = %.15e\n', t);
	fprintf('beta = %.15e\n', beta);
	
	fprintf('Maximum absolute error = %.15e\n', ...
	maximum_absolute_error);
	
	fprintf('Relative L-infinity error = %.15e\n', ...
	relative_Linf_error);
	
	fprintf('Relative L2 error = %.15e\n', ...
	relative_L2_error);
	
	%% Plot analytical and numerical CPV solutions
	figure_size_in = [3.45, 2.30];
	
	axis_line_width = 0.9;
	curve_line_width = 1.8;
	
	axis_font_size  = 10;
	label_font_size = 12;
	legend_font_size = 10;
	
	marker_size    = 3;
	marker_spacing = 50;
	
	fig = figure( ...
	'Visible', 'on', ...
	'Color', 'w', ...
	'Renderer', 'painters');
	
	set(fig, ...
	'Units', 'inches', ...
	'Position', [1, 1, figure_size_in]);
	
	layout = tiledlayout( ...
	fig, ...
	1, ...
	1, ...
	'Padding', 'compact', ...
	'TileSpacing', 'compact');
	
	ax = nexttile(layout);
	
	hold(ax, 'on');
	
	set(ax, ...
	'TickDir', 'out', ...
	'LineWidth', axis_line_width, ...
	'FontSize', axis_font_size, ...
	'XAxisLocation', 'bottom', ...
	'YAxisLocation', 'left');
	
	%% Plot analytical total solution first
	h_analytical_left = plot( ...
	ax, ...
	x(mask_left), ...
	1.0e3.*eta_analytical(mask_left), ...
	'b-.', ...
	'LineWidth', 2.0);
	
	if any(mask_right)
	h_analytical_right = plot( ...
	ax, ...
	x(mask_right), ...
	1.0e3.*eta_analytical(mask_right), ...
	'b-.', ...
	'LineWidth', 2.0);
	
	h_analytical_right.HandleVisibility = 'off';
	end
	%% Plot steady solution
	h_steady = plot( ...
	ax, ...
	x, ...
	1.0e3.*eta_steady, ...
	'k-', ...
	'LineWidth', 1.5);
	
	%% Plot analytical transient contribution
	h_transient_left = plot( ...
	ax, ...
	x(mask_left), ...
	1.0e3.*eta_transient(mask_left), ...
	'm:', ...
	'LineWidth', 1.5);
	
	if any(mask_right)
	h_transient_right = plot( ...
	ax, ...
	x(mask_right), ...
	1.0e3.*eta_transient(mask_right), ...
	'm:', ...
	'LineWidth', 1.5);
	
	h_transient_right.HandleVisibility = 'off';
	end
	
	%% Plot direct numerical CPV solution using markers
	index_left = find(mask_left);
	
	h_numerical_cpv = plot( ...
	ax, ...
	x(index_left), ...
	1.0e3.*eta_cpv_numerical(index_left), ...
	'LineStyle', 'none', ...
	'Color', [0.49, 0.18, 0.56], ...
	'Marker', 'o', ...
	'MarkerIndices', ...
	1:marker_spacing:numel(index_left), ...
	'MarkerSize', marker_size, ...
	'MarkerFaceColor', 'w', ...
	'MarkerEdgeColor', 'auto', ...
	'LineWidth', curve_line_width - 1.0);
	
	if any(mask_right)
	
	index_right = find(mask_right);
	
	h_numerical_cpv_right = plot( ...
	ax, ...
	x(index_right), ...
	1.0e3.*eta_cpv_numerical(index_right), ...
	'LineStyle', 'none', ...
	'Color', [0.49, 0.18, 0.56], ...
	'Marker', 'o', ...
	'MarkerIndices', ...
	1:marker_spacing:numel(index_right), ...
	'MarkerSize', marker_size, ...
	'MarkerFaceColor', 'w', ...
	'MarkerEdgeColor', 'auto', ...
	'LineWidth', curve_line_width - 1.0);
	
	h_numerical_cpv_right.HandleVisibility = 'off';
	end
	
	%% Axis limits
	xlim(ax, [-L/2.0, L/2.0]);
	ylim(ax, [-5.0, 9.0]);
	yticks(ax, [-4.0, 0.0, 4.0, 8.0]);
	
	%% Mark the front x = t
	y_limits = ylim(ax);
	
	line( ...
	ax, ...
	[t, t], ...
	y_limits, ...
	'LineStyle', '--', ...
	'Color', [0, 0, 0], ...
	'LineWidth', 1.2, ...
	'HandleVisibility', 'off');
	
	y_text = y_limits(2) ...
	-0.05.*(y_limits(2) - y_limits(1));
	
	text( ...
	ax, ...
	t, ...
	y_text, ...
	'$x=t$', ...
	'Interpreter', 'latex', ...
	'FontSize', axis_font_size, ...
	'HorizontalAlignment', 'center', ...
	'VerticalAlignment', 'top', ...
	'BackgroundColor', 'w', ...
	'Margin', 1);
	
	%% Draw the upper and right frame lines
	set(ax, 'Box', 'off');
	
	delete(findall(ax, 'Tag', 'TopRightFrame'));
	
	x_limits = xlim(ax);
	y_limits = ylim(ax);
	
	line( ...
	ax, ...
	[x_limits(1), x_limits(2)], ...
	[y_limits(2), y_limits(2)], ...
	'Color', 'k', ...
	'LineWidth', axis_line_width, ...
	'Clipping', 'off', ...
	'HandleVisibility', 'off', ...
	'Tag', 'TopRightFrame');
	
	line( ...
	ax, ...
	[x_limits(2), x_limits(2)], ...
	[y_limits(1), y_limits(2)], ...
	'Color', 'k', ...
	'LineWidth', axis_line_width, ...
	'Clipping', 'off', ...
	'HandleVisibility', 'off', ...
	'Tag', 'TopRightFrame');
	
	%% Legend
	legend_handle = legend( ...
	ax, ...
	[ ...
	h_analytical_left, ...
	h_steady, ...
	h_transient_left, ...
	h_numerical_cpv ...
	], ...
	{ ...
		'$\eta$', ...
		'$\eta_s$', ...
		'$\eta_{\mathrm{tr}}$', ...
		'$\eta_{\mathrm{CPV}}$' ...
	}, ...
	'Location', 'northwest', ...
	'Interpreter', 'latex', ...
	'FontSize', legend_font_size, ...
	'Box', 'on');
	
	legend_handle.EdgeColor = 0.4.*[1, 1, 1];
	legend_handle.LineWidth = 0.6;
	legend_handle.Color = 'w';
	legend_handle.ItemTokenSize = [12, 9];
	
	%% Axis labels
	xlabel( ...
	ax, ...
	'$x$', ...
	'Interpreter', 'latex', ...
	'FontSize', label_font_size);
	
	ylabel( ...
	ax, ...
	'$10^3 y$', ...
	'Interpreter', 'latex', ...
	'FontSize', label_font_size);
	
	drawnow;
	
	%% Save figure
	output_name = sprintf( ...
	'figure6_alpha0_analytical_numerical_cpv_t%04d', ...
	time_index);
	
	exportgraphics( ...
	fig, ...
	fullfile(output_directory, [output_name, '.pdf']), ...
	'ContentType', 'vector', ...
	'BackgroundColor', 'white');
	
	exportgraphics( ...
	fig, ...
	fullfile(output_directory, [output_name, '.eps']), ...
	'ContentType', 'vector', ...
	'BackgroundColor', 'white');
	
	exportgraphics( ...
	fig, ...
	fullfile(output_directory, [output_name, '.png']), ...
	'Resolution', 900, ...
	'BackgroundColor', 'white');
	end
	
	fprintf('Figures saved in: %s\n', output_directory);
