/**
# Two-fluid capillary-gravity waves generated by a localized pressure forcing

This code reproduces the numerical simulations used in Figure 10 of the
manuscript. A localized Lorentzian pressure distribution is applied at the
initially flat interface between two fluids of infinite-depth approximation.
Both fluids have a uniform horizontal base velocity.

The simulation is dimensional and uses CGS units.
*/

#include "navier-stokes/centered.h"
#include "two-phase.h"
#include "reduced.h"
#include "tension.h"


/**
## Physical parameters

The lower and upper fluids have density ratio

$$
\rho_r = \frac{\rho_u}{\rho_l}=10^{-3}.
$$

The computational domain is a square of side length $L$.
*/

#define g_    981.0
#define rho_w 1.0
#define rho_a (rho_w/1000.0)
#define L     75.5996


/**
## Boundary conditions

A uniform horizontal base velocity

$$
U = 26.7046\ {\rm cm/s}
$$

is imposed. The normal velocity is zero at the top and bottom boundaries.
*/

u.t[top]    = dirichlet(26.7046);
u.n[top]    = dirichlet(0.);

u.t[bottom] = dirichlet(26.7046);
u.n[bottom] = dirichlet(0.);

u.n[left]   = dirichlet(26.7046);
u.t[left]   = dirichlet(0.);

u.n[right]  = dirichlet(26.7046);
u.t[right]  = dirichlet(0.);


/**
The pressure is fixed to zero at the right boundary and a zero normal
pressure gradient is imposed at the other boundaries.
*/

p[right]  = dirichlet(0.);
pf[right] = dirichlet(0.);

p[left]   = neumann(0.);
pf[left]  = neumann(0.);

p[top]    = neumann(0.);
pf[top]   = neumann(0.);

p[bottom]  = neumann(0.);
pf[bottom] = neumann(0.);


/**
A zero normal gradient is imposed on the volume fraction at all boundaries.
*/

f[left]   = neumann(0.);
f[right]  = neumann(0.);
f[top]    = neumann(0.);
f[bottom] = neumann(0.);


/**
## Main function

The origin is placed at the centre of the computational domain. Gravity acts
in the negative $y$ direction. The surface tension coefficient is

$$
T = 72\ {\rm dyn/cm}.
$$

The initial grid contains $256^2$ cells and is subsequently adapted using
wavelet-based mesh refinement.
*/

int main()
{
  origin (-L/2., -L/2.);

  G.y = -g_;

  rho1 = rho_w;
  rho2 = rho_a;

  f.sigma = 72.0;

  // Inviscid simulations
  // mu1 = 0.;
  // mu2 = 0.;

  size (L);
  init_grid (256);

  run();
}


/**
## Localized pressure forcing

A Lorentzian pressure distribution

$$
p_e(x) =
\frac{F_0}{\pi}
\frac{b}{b^2+x^2}
$$

is applied at the interface, where

$$
F_0 = 0.01T.
$$

The width of the pressure distribution is taken to be one local grid-cell
width, $b=\Delta$. In the limit $b\rightarrow 0$, the Lorentzian distribution
approaches a Dirac delta distribution.

The pressure forcing is introduced as an interfacial acceleration using the
VOF gradient.
*/

event acceleration (i++)
{
  face vector ia = a;
  scalar pressure_phi[];

  double T_      = 72.0;
  double prefac_ = 0.01;

  foreach_face(y) {

    double b_ = Delta;

    pressure_phi[] =
      (prefac_*T_*b_)/(pi*(sq(b_) + sq(x)));

    ia.y[] += alpha.y[]/(fm.y[] + SEPS)*
      pressure_phi[]*(f[] - f[0,-1])/Delta;
  }
}


/**
## Initial condition

The interface is initially flat at $y=0$. The lower fluid occupies $y<0$
and the upper fluid occupies $y>0$. Both fluids initially move with the
uniform horizontal velocity $U$.
*/

event init (t = 0)
{
  fraction (f, -y);
  boundary ({f});

  foreach() {
    u.x[] = 26.7046;
    u.y[] = 0.;
  }

  boundary ({u, p});
}


/**
## Time-step information

The simulation time and time-step size are written to standard output at
every iteration.
*/

event logfile2 (i++)
{
  if (i == 0)
    fprintf (stdout, "t dt\n");

  fprintf (stdout, "%g %g\n", t, dt);
  fflush (stdout);
}


/**
## Adaptive mesh refinement

The mesh is adapted using the volume fraction, both velocity components and
the interface curvature. The maximum refinement level is 13 and the minimum
level is 5.

Curvature-based refinement is restricted to

$$
-30 < x < 30\ {\rm cm},
$$

which leaves less-refined buffer regions close to the left and right
boundaries.
*/

double uemax = 0.001;

#define fErr   (1e-3)
#define KErr   (1e-6)
#define VelErr (uemax)

#define MAXLEVEL 13

scalar KAPPA[];

event adapt (i++)
{
  curvature (f, KAPPA);

  foreach() {

    // Curvature is undefined away from the reconstructed interface.
    if (KAPPA[] == nodata)
      KAPPA[] = 0.;

    // Disable curvature-based refinement in the boundary buffer regions.
    if (x < -30. || x > 30.)
      KAPPA[] = 0.;
  }

  boundary ((scalar *) {KAPPA});

  adapt_wavelet ((scalar *) {f, u.x, u.y, KAPPA},
                 (double[]) {fErr, VelErr, VelErr, KErr},
                 MAXLEVEL, 5);
}


/**
## Output

A Basilisk dump file is written every $0.01$ s up to $t=5.02$ s. These
restart files contain the complete simulation state and can subsequently be
used for post-processing.
*/

event dump_i1 (t = 0; t += 0.01; t <= 5.02)
{
  char name4[128];
  sprintf (name4, "./data/snapshot-%g", t);

  scalar pid[];

  foreach()
    pid[] = fmod(pid()*(npe() + 37), npe());

  boundary ({pid});

  dump (name4);
}