"""
    generate_cg_overlays.jl

Generates three static overlay PNGs for capillary-gravity figures:
  fig7_overlay.png   — I4 at t=0.34
  fig8_overlay.png   — Full IVP at t=367.35
  fig10_overlay.png  — IVP vs nonlinear simulation at t_dim=25s

MATLAB data loaded from docs/src/assets/cg_*.csv (generated by
  matlab/generate_cg_comparison_data.m)

Usage:
    julia --project=scripts scripts/generate_cg_overlays.jl
"""

using ForcedInterfacialWaves
using Plots, LaTeXStrings
using DelimitedFiles

gr()

plot_font = "Computer Modern"
default(fontfamily=plot_font, linewidth=3, framestyle=:box, label=nothing,
        grid=false, fg_legend=false, background_color_legend=false)

ASSETS = joinpath(@__DIR__, "..", "docs", "src", "assets")
NBDIR  = joinpath(@__DIR__, "..", "notebooks")

load_csv(f) = readdlm(joinpath(ASSETS, f), ',', Float64)

# ── Parameters and full Julia grid ────────────────────────────────────────────
p = compute_cg_parameters()
x = make_cg_xgrid(p; Nx=2001, xlim=(-15.0, 15.0))

# ── Uniform sparse markers every 8 pts of the 400-pt MATLAB grid ─────────────
mi = 1:8:400   # ~50 markers

# ═══════════════════════════════════════════════════════════════════════════════
# Fig 7 — I4 component at t = 0.34
# ═══════════════════════════════════════════════════════════════════════════════
t_I4 = 0.34
I4_julia = compute_cg_I4_profile(x, t_I4, p; method=:threaded_vector)
y_julia_7 = -(1/(2π)) .* I4_julia

mat7 = load_csv("cg_I4_t034.csv")
xm7  = mat7[:, 1]
ym7  = mat7[:, 2]

fig7 = plot(x, y_julia_7 .* 1e3; color="purple",
            guidefontsize=16, tickfontsize=14, legendfontsize=13,
            xlabel=L"x", ylabel=L"\frac{-\mathbb{I}_{4}}{2\pi} \times 10^{3}",
            xlims=(-10,10), size=(800,400),
            label=L"\mathrm{Julia}")
scatter!(xm7[mi], ym7[mi] .* 1e3; shape=:circle, ms=5, msw=1.2,
         mc=:orange, markerstrokecolor=:orange,
         label=L"\mathrm{MATLAB}")

savefig(fig7, joinpath(ASSETS, "fig7_overlay.png"))
println("Saved fig7_overlay.png")

# ═══════════════════════════════════════════════════════════════════════════════
# Fig 8 — Full IVP at t = 367.35
# ═══════════════════════════════════════════════════════════════════════════════
t_fig8 = 367.35
sol_8  = solve(ForcedGCProblem(p, x, t_fig8); method=IVP())

mat8    = load_csv("cg_ivp_eta_t36735.csv")
xm8     = mat8[:, 1]
ym8_eta = mat8[:, 2]
ym8_tr  = mat8[:, 3]

fig8 = plot(x, sol_8.η .* 1e3; label=L"\eta\ \mathrm{Julia}", color="blue", ls=:dash,
            guidefontsize=16, tickfontsize=14, legendfontsize=13,
            xlabel=L"x", ylabel=L"\eta \times 10^{3}",
            xlims=(-10,10), ylims=(-4.8, 8.2), yticks=[-4,0,4,8],
            legend=:outerright, size=(800,400))
plot!(x, sol_8.η_transient .* 1e3; label=L"\eta_{tr}\ \mathrm{Julia}",
      color="magenta", ls=:dot)
scatter!(xm8[mi], ym8_eta[mi] .* 1e3; shape=:circle, ms=5, msw=1.2,
         mc=:blue, markerstrokecolor=:blue,
         label=L"\eta\ \mathrm{MATLAB}")
scatter!(xm8[mi], ym8_tr[mi] .* 1e3; shape=:circle, ms=5, msw=1.2,
         mc=:red, markerstrokecolor=:red,
         label=L"\eta_{tr}\ \mathrm{MATLAB}")

savefig(fig8, joinpath(ASSETS, "fig8_overlay.png"))
println("Saved fig8_overlay.png")

# ═══════════════════════════════════════════════════════════════════════════════
# Fig 10 — IVP vs simulation at t_dim = 25 s
# ═══════════════════════════════════════════════════════════════════════════════
t_dim = 25
t_sim = t_dim / (100 * p.t_c)
sol_sim = solve(ForcedGCProblem(p, x, t_sim); method=IVP())

# Simulation (Basilisk) data
data_bsk = sortslices(
    readdlm(joinpath(NBDIR, "if_$(t_dim).csv"), ',', Float64; skipstart=1),
    dims=1, by=r -> r[6])
x_bsk = data_bsk[:, 6] ./ p.l_c
y_bsk = data_bsk[:, 7] ./ p.l_c

# MATLAB IVP
mat10 = load_csv("cg_ivp_eta_t25s.csv")
xm10  = mat10[:, 1]
ym10  = mat10[:, 2]

fig10 = plot(x, sol_sim.η .* 1e3; label=L"\eta\ \mathrm{Julia}", color="blue", ls=:dash,
             guidefontsize=16, tickfontsize=14, legendfontsize=13,
             xlabel=L"x", ylabel=L"\eta \times 10^{3}",
             xlims=(-6,10), ylims=(-6, 8.2), yticks=[-4,0,4,8],
             legend=:outerright, size=(800,400))
scatter!(xm10[mi], ym10[mi] .* 1e3; shape=:circle, ms=5, msw=1.2,
         mc=:orange, markerstrokecolor=:orange,
         label=L"\eta\ \mathrm{MATLAB}")
plot!(x_bsk, y_bsk .* 1e3; label="Simulation", color="red", ls=:dot)

savefig(fig10, joinpath(ASSETS, "fig10_overlay.png"))
println("Saved fig10_overlay.png")
println("Done.")
