[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForcedInterfacialWaves = "e5219359-20f7-449b-9a6e-3764ada0d72e"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[sources]
ForcedInterfacialWaves = {path = "/Users/nikhil/ForcedInterfacialWaves.jl/"}
